export interface TailwindClassProps {
    default?: string;
    hover?: string;
    focus?: string;
    active?: string;
    first?: string;
    last?: string;
    odd?: string;
    even?: string;
    selection?: string;
    lg?: string;
    sm?: string;
    xl?: string;
    _2xl?: string;
    dark?: string;
    print?: string;
    ltr?: string;
    rtl?: string;
    open?: string;
    marker?: string;
    placeholder?: string;
    after?: string;
    before?: string;
    file?: string;
    backdrop?: string;
    landscape?: string;
    portrait?: string;
    "group-hover"?: string;
    "first-line"?: string;
    "first-letter"?: string;
    [key: string]: string;
}
declare const tailwindclass: (props: TailwindClassProps) => string;
export default tailwindclass;
